### ISSUE TITLE
What is the exe_path property used for?

### ISSUE THREAD

**Issue by marnel-estrada** [aschearer/UnityCloudBuildSteamUploader#4]
I'm trying to upload a Mac build but there's no exe. When I used <GameName>.app, Steam SDK fails:

Couldn't read file 'E:\InstalledPrograms\UnityCloudBuildSteamUploader\Steamworks_SDK\content\academia_academia-mac_content\Academia.app'
DRM wrap failed with EResult 9 (File Not Found)

**Comment by marnel-estrada** [comment]
As a work around, I made a new publish batch file and removed DRM wrapping in it. I then used this file in Upload-SteamContent.ps1.

This only works for Upload-SteamContent.ps1, though. Not on BuildUploader.Console.exe.

**Comment by aschearer** [comment]
Hi @marnel-estrada thanks for the bug report. The exe_path is used by the Steam DRM wrapper. I'm guessing for mac builds you could provide the .app file, but I haven't tried. I think removing the DRM functionality with a new script makes sense. 

If you'd like to work with me to come up with a more data-driven, generic solution I'd love your help.

**Comment by marnel-estrada** [comment]
For Mac builds, the .app is not really a file. It's a folder. I don't know how DRM wrapping works in Mac.

Maybe provide an option to opt for DRM wrapping or not. This could just be added in BuildUploader.Console.exe.config. A boolean variable will suffice.

**Comment by aschearer** [comment]
I've removed DRM support from the latest version as it seems the command line options changed. If you'd like to contribute some changes to improve mac support more generally, that'd be great!
