### ISSUE TITLE
Trouble bypassing Steam Guard

### ISSUE THREAD

**Issue by TheSLAP** [aschearer/UnityCloudBuildSteamUploader#5]
I can successfully login using "Upload-SteamContent" which prompts the Steam Guard protection. However, as soon as I start BuildUpload.Console (using the same powershell), it gets stuck at "Invoking Steamworks SDK to upload build" and then I receive a Steam Guard notification on my phone. Is there anyway to bypass Steam Guard continually?

**Comment by aschearer** [comment]
Hi, that's not been my experience so additional details are needed.

**Comment by aschearer** [comment]
Hi, that's not been my experience so additional details are needed.
